version: "3.7"
services:
#RTSP 
   rtsp-server:
    image: aler9/rtsp-simple-server
    container_name: rtsp-server
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - RTSP_PROTOCOLS=tcp
#NODE-RED
   node-red:
    container_name: taky-rtsp-sidecar
    user: "1000"
    network_mode: host
    restart: unless-stopped
    image: skadakar/taky-rtsp-sidecar:latest
    environment:
      - COT_IP=127.0.0.1
      - COT_PORT=8089
    volumes:
      - /root/node-red/certs/ca.pem:/data/certs/ca.pem
      - /root/node-red/certs/server.pem:/data/certs/server.pem
      - /root/node-red/certs/server.key:/data/certs/server.key
